### ISSUE TITLE
It seems the parallel code does not work for mac nodes

### ISSUE THREAD

**Issue by houtanb** [DragonflyTeam/dragonfly#7]
Specifically, `AnalyseComputationalEnvironment` contains no `ismac` statements. Thus, describing a node as `unix` we encounter a problem trying to determine the number of processors on the system. On macOS, the command `grep processor /proc/cpuinfo` as seen here: https://github.com/DragonflyTeam/dragonfly/blob/44552c2c2acd7e42369b4b255eb4d13e63b024e3/SrcDragonfly/AnalyseComputationalEnvironment.m#L585 does not exist. A simpler way to get the number of processors on both macOS and a *nix system would be to use the `nproc` command.

**Comment by houtanb** [comment]
As a followup, given the config file:
```
[cluster]
Name=Lion
Members=n2 n1

[node]
Name = n1
ComputerName = localhost
CPUnbr = [1:1]
MatlabOctavePath = matlab
SingleCompThread = true
OperatingSystem = unix

[node]
Name = n2
ComputerName = localhost
CPUnbr = [2:2]
MatlabOctavePath = matlab
SingleCompThread = true
OperatingSystem = unix
```
running `dynare example1.mod parallel_test` with the files in `matlab/parallel` in Dynare 4.6, we have
```
Testing computer -> localhost <- ...


Check on Local Variable ..... Ok!

Checking Hardware please wait ...
Hardware has 8 Cpu/Cores!
User requires 1 Cpu/Cores!
Warning! There are unused CPU's!


Test for Cluster computation, computer localhost ..... Passed!




Testing computer -> localhost <- ...


Check on Local Variable ..... Ok!

Checking Hardware please wait ...
Hardware has 8 Cpu/Cores!
User requires 1 Cpu/Cores!
Warning! There are unused CPU's!


Test for Cluster computation, computer localhost ..... Passed!


AnalyseComputationalEnvironment returned with Error Code: 2.2
```
Running the same command using dragonfly on macOS we have
```
Testing computer -> localhost <- ...


Check on Local Variable ..... Ok!


Checking Hardware please wait ...
It is impossible determine the number of Cpu/Processor avaiable on this machine!

ErrorCode 2.

Check the command "$less /proc/cpuinfo" ... !

AnalyseComputationalEnvironment returned with Error Code: 2
```
which seems like a regression on macOS

**Comment by rattoma** [comment]
@houtanb indeed, @giovanma has encountered the same problems. He made recently a few patches (not committed/pushed), which he can share with you, so that it should be faster to make bug fix commits. Indeed, one issue is that DragonFly and Parallel DYNARE diverged, so that all fixes done to parallel DYNARE in the last years have not been systematically cherry-picked.

**Comment by houtanb** [comment]
Ah, ok, yes, it would be good to push his changes and make dragonfly work with macOS as well

**Comment by rattoma** [comment]
@houtanb, while merging from @giovanma, I notice that dragonfly misses skipline(), which is a dynare utility. For the general usage outside dynare, I would just include skipline() in the dragonfly distrubution. is this OK?

**Comment by houtanb** [comment]
Yes, it's OK. Just not in the source folder. It should be in a utilities folder....

**Comment by houtanb** [comment]
@rattoma are you taking charge of merging @giovanma's files? If so, I will wait for that before proceeding....

**Comment by rattoma** [comment]
yes I am almost there

---
Marco Ratto,
Finance and Economy
Joint Research Centre
European Commission,
TP 581, 21027  ISPRA(VA), ITALY
Tel: +39 0332 78 3794
marco.ratto@ec.europa.eu

________________________________________

**Comment by rattoma** [comment]
@houtanb. pls check if b01dfc5c3769c789679239893db93ef5148ecaa4 works.
pls note that there might be the need to further merge features/fixes from dynare parallel into the diverged dragonfly development to fully recover the behavior of dynare parallel.

**Comment by houtanb** [comment]
I'm going to move the discussion to https://gitlab.com/dragonflytool/dragonfly/issues/1
